# Generated by Django 5.1.7 on 2025-03-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testappvariety',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
